openshift/run-once-duration-override-operator

- Makefile
- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
- test/e2e/bindata/assets/08_crd.yaml
- test/e2e/bindata/assets/09_cr.yaml
- test/e2e/operator_test.go
- update crd + cr
- fix the sa asset path
> Update test/e2e manifests

- README.md
So we can test the bundle image built in Brew
> Update README with instructions on how to build the index image from the bundle image

- OWNERS
> Set repository component to run-once-duration-override

- README.md
> Rename ns in readme

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> CSV: set minKubeVersion to 1.26.0

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> WRKLDS-780: Bump CSV manifest to 1.0.1

- README.md
> Extend readme with releases

- cmd/testutil/json2yaml/json2yaml.go
- cmd/testutil/yaml2json/yaml2json.go
- pkg/apis/runoncedurationoverride/v1/override.go
- pkg/cert/bundle.go
- pkg/cert/client_ca.go
- pkg/dynamic/ensurer.go
- pkg/runoncedurationoverride/internal/condition/builder.go
- pkg/secondarywatch/start.go
This PR adds error handlers and trivial changes to suppress code scan warnings.
> Refactor code to align with code scan results

- README.md
> no-op to re-trigger cpass integration

- README.md
> No-op to retrigger cpass build

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> NO-JIRA: csv: fix operator naming schema

- Makefile
> OCPBUGS-25123: Makefile: add strictfipsruntime build tag

- Makefile
- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> NO-JIRA: Sync with master

- README.md
> no-jira: readme: update releases

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
- test/e2e/bindata/assets/07_deployment.yaml
- test/e2e/operator_test.go
- bump CSV to 1.1.1
- bump e2e operand version to 1.1.1/4.16
> WRKLDS-1047: Prepare 1.1.1 release

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> NO-JIRA: csv: Set required Infrastructure Annotations

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> WRKLDS-1047: csv: fix annotation

- deploy/07_deployment.yaml
- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
- pkg/asset/daemonset.go
operands:
- https://issues.redhat.com/browse/WRKLDS-1133
- https://issues.redhat.com/browse/WRKLDS-1137
- https://issues.redhat.com/browse/WRKLDS-1140
operator: https://issues.redhat.com/browse/WRKLDS-1135
> WRKLDS-1133: Set readOnlyRootFilesystem to true

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> WRKLDS-1271: CSV: claim features.operators.openshift.io/disconnected as true

- deploy/07_deployment.yaml
- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> operand: fix containers[].securityContext.readOnlyRootFilesystem field name

- README.md
- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> WRKLDS-1247: Prepare rodoo 1.2.0 release

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> WRKLDS-1413: Prepare 1.0.2 release

- Dockerfile
- bundle.Dockerfile
- hack/replace-image.sh
> WRKLDS-1505: Dockerfiles for operator and bundle

- Dockerfile
- bundle.Dockerfile
- hack/replace-image.sh
> no-jira: Sync with main

- .tekton/run-once-duration-override-operator-4-18-pull-request.yaml
- .tekton/run-once-duration-override-operator-4-18-push.yaml
> WRKLDS-1505: [tekton]: build source image, hermetic builds, extend the list of archs

- .tekton/run-once-duration-override-operator-4-18-pull-request.yaml
- .tekton/run-once-duration-override-operator-4-18-push.yaml
> no-jira: [tekton]: enable snyk

- v4.18/catalog.Dockerfile
> no-jira: Dockerfile fbc

- Dockerfile
- bundle.Dockerfile
- hack/replace-image.sh
> no-jira: Dockerfiles for operator and bundle

- .tekton/run-once-duration-override-operator-4-16-pull-request.yaml
- .tekton/run-once-duration-override-operator-4-16-push.yaml
- .tekton/run-once-duration-override-operator-bundle-4-16-pull-request.yaml
- .tekton/run-once-duration-override-operator-bundle-4-16-push.yaml
> no-jira: [tekton]: build source image, hermetic builds, extend the list of archs

- bundle.Dockerfile
> WRKLDS-1635: bump(bundle.Dockerfile): pin operand and operator images

- .tekton/run-once-duration-override-operator-fbc-4-18-pull-request.yaml
- .tekton/run-once-duration-override-operator-fbc-4-18-push.yaml
> no-jira: Sync tekton jobs to pick up the latest improvements

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> WRKLDS-1640: bump(rodoo)=1.2.1

- bundle.Dockerfile
> WRKLDS-1640: Point bundle.Dockerfile to the latest operator image

- README.md
> no-jira: no-op: to re-trigger build pipeline

- v4.18/catalog-template.json
- v4.18/catalog/run-once-duration-override-operator/catalog.json
> WRKLDS-1635: Update fbc with the latest 1.2.1 release

- .tekton/run-once-duration-override-operator-bundle-4-18-pull-request.yaml
- .tekton/run-once-duration-override-operator-bundle-4-18-push.yaml
> no-jira: [tekton]: extend bundle configs with required tasks

- .tekton/run-once-duration-override-operator-4-18-pull-request.yaml
- .tekton/run-once-duration-override-operator-4-18-push.yaml
> no-jira: [tekton]: extend operator configs with required tasks

- bundle.Dockerfile
> bundle: point to non-staging registry to use a snapshot for both staging and final release

- bundle.Dockerfile
> bundle: point operator image to the latest one

- bundle.Dockerfile
> no-jira: Bump bundle to the latest operator image reference

- .tekton/run-once-duration-override-operator-4-20-pull-request.yaml
- .tekton/run-once-duration-override-operator-4-20-push.yaml
- .tekton/run-once-duration-override-operator-bundle-4-20-pull-request.yaml
- .tekton/run-once-duration-override-operator-bundle-4-20-push.yaml
> Bump tekton to 4.20

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> csv: add relatedImages

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> no-jira: csv: add relatedImages

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> no-jira: csv: bump to 1.2.2

- .tekton/run-once-duration-override-operator-4-20-pull-request.yaml
- .tekton/run-once-duration-override-operator-4-20-push.yaml
> feat(.tekton): sync with the latest Konflux configuration changes

- .tekton/run-once-duration-override-operator-4-20-pull-request.yaml
- .tekton/run-once-duration-override-operator-4-20-push.yaml
- .tekton/run-once-duration-override-operator-bundle-4-20-pull-request.yaml
- .tekton/run-once-duration-override-operator-bundle-4-20-push.yaml
- bundle.Dockerfile
> chore: sync with release 4.20

- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> feat(csv): enable automatic namespace creation

- bundle.Dockerfile
- manifests/runoncedurationoverride-operator.clusterserviceversion.yaml
> fix(bundle.Dockerfile): set the right target operator/operand images
